import { getCardImage } from './cardImages';
import type { CourtCard, PlayerCard, RuleCard, ActionCard } from './gameState';

const withImages = <T extends { id: string }>(cards: T[]): Array<T & { image?: string }> =>
  cards.map((card) => ({
    ...card,
    image: getCardImage(card.id),
  }));

/**
 * MASTER CARD LISTS
 * These are all cards that exist for each category.
 */

export const allCourtCards: CourtCard[] = withImages([
  {
    category: 'court',
    type: 'guild',
    name: 'Mining Interest',
    id: 'cc-01',
    number: 1,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Construction Union',
    id: 'cc-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Gatekeepers',
    id: 'cc-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Shipping Interest',
    id: 'cc-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Skirmishers',
    id: 'cc-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Arms Union',
    id: 'cc-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Lattice Spies',
    id: 'cc-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Silver-Tongues',
    id: 'cc-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Sworn Guardians',
    id: 'cc-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Elder Brokers',
    id: 'cc-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Populist Demands',
    id: 'cc-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Council Intrigue',
    id: 'cc-12',
    number: 12,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Diplomatic Fiasco',
    id: 'cc-13',
    number: 13,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Song of Freedom',
    id: 'cc-14',
    number: 14,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Blight Looms',
    id: 'cc-15',
    number: 15,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Tool-Priests',
    id: 'l-01',
    number: 1,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Galactic Rifles',
    id: 'l-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Sprinter Drives',
    id: 'l-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Mirror Plating',
    id: 'l-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Hidden Harbors',
    id: 'l-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Signal Breaker',
    id: 'l-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Repair Drones',
    id: 'l-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Gate Ports',
    id: 'l-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Cloud Cities',
    id: 'l-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Living Structures',
    id: 'l-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Gate Stations',
    id: 'l-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Railgun Arrays',
    id: 'l-12',
    number: 12,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Ancient Holdings',
    id: 'l-13',
    number: 13,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Seeker Torpedoes',
    id: 'l-14',
    number: 14,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Imperial Authority',
    id: 'F1-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Dealmakers',
    id: 'F1-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Council Intrigue',
    id: 'F1-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Tax Collectors',
    id: 'F1-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Hunter Squads',
    id: 'F1-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Empire Falls',
    id: 'F1-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Lesser Regent',
    id: 'F1-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Lesser Regent',
    id: 'F1-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Council Insiders',
    id: 'F1-16',
    number: 16,
  },
   {
    category: 'court',
    type: 'guild',
    name: 'Galactic Bards',
    id: 'F1-17',
    number: 17,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Imperial Defectors',
    id: 'F1-18',
    number: 18,
  },
   {
    category: 'court',
    type: 'vox',
    name: 'Imperial Defectors',
    id: 'F1-19',
    number: 19,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Lesser Regent',
    id: 'F1-20',
    number: 20,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Lesser Regent',
    id: 'F1-21',
    number: 21,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Parade Fleets',
    id: 'F2-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Book of Liberation',
    id: 'F2-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Political Intrigue',
    id: 'F2-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Political Intrigue',
    id: 'F2-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Political Intrigue',
    id: 'F2-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Construction Union',
    id: 'F2-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Construction Union',
    id: 'F2-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Admin Union',
    id: 'F2-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Admin Union',
    id: 'F2-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Armistice',
    id: 'F2-16',
    number: 16,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Armistice',
    id: 'F2-17',
    number: 17,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Spirit of Freedom',
    id: 'F2-24',
    number: 24,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Merchant League',
    id: 'F3-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Elder Broker',
    id: 'F3-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Relic Fence',
    id: 'F3-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Prison Wardens',
    id: 'F3-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Material Cartel',
    id: 'F3-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Fuel Cartel',
    id: 'F3-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Weapon Cartel',
    id: 'F3-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Psionic Cartel',
    id: 'F3-10',
    number: 11,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Relic Cartel',
    id: 'F3-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Prospectors',
    id: 'F3-22',
    number: 22,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Extortion',
    id: 'F3-23',
    number: 23,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Extortion',
    id: 'F3-24',
    number: 24,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Guild Investigators',
    id: 'F4-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Guild Overseers',
    id: 'F4-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Material Liaisons',
    id: 'F4-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Fuel Liaisons',
    id: 'F4-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Weapons Liaisons',
    id: 'F4-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Relic Liaisons',
    id: 'F4-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Psionic Liaisons',
    id: 'F4-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Diplomatic Fiasco',
    id: 'F4-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Guild Struggle',
    id: 'F4-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Guild Fair',
    id: 'F4-16',
    number: 16,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Material Guildmasters',
    id: 'F4-17',
    number: 17,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Fuel Guildmasters',
    id: 'F4-18',
    number: 18,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Weapons Guildmasters',
    id: 'F4-19',
    number: 19,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Relic Guildmasters',
    id: 'F4-20',
    number: 20,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Psionic Guildmasters',
    id: 'F4-21',
    number: 21,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Guilds Withdraw',
    id: 'F4-22',
    number: 22,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Golem Beacon',
    id: 'F5-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Golem Hearth',
    id: 'F5-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Stone-Speakers',
    id: 'F5-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Unstable Harvester',
    id: 'F5-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Unstable Seeker',
    id: 'F5-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Unstable Protector',
    id: 'F5-10',
    number: 11,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Unstable Warrior',
    id: 'F5-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Librarians',
    id: 'F5-13',
    number: 13,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Golem Worship',
    id: 'F5-17',
    number: 17,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Golem Worship',
    id: 'F5-18',
    number: 18,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Golem Worship',
    id: 'F5-19',
    number: 19,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Informants',
    id: 'F6-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Loyal Engineers',
    id: 'F6-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Loyal Pilots',
    id: 'F6-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Loyal Marines',
    id: 'F6-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Loyal Empaths',
    id: 'F6-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Loyal Keepers',
    id: 'F6-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Galactic Bards',
    id: 'F6-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Spacing Union',
    id: 'F6-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Arms Union',
    id: 'F6-12',
    number: 12,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Outrage Spreads',
    id: 'F6-13',
    number: 13,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Outrage Spreads',
    id: 'F6-14',
    number: 14,
  },
  {
    category: 'court',
    type: 'lore',
    name: "People's Hero",
    id: 'F6-17',
    number: 17,
  },
  {
    category: 'court',
    type: 'vox',
    name: "Terror Strike",
    id: 'F6-20',
    number: 20,
  },
  {
    category: 'court',
    type: 'vox',
    name: "Terror Strike",
    id: 'F6-21',
    number: 21,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Spacing Union',
    id: 'F6-22',
    number: 22,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Arms Union',
    id: 'F6-23',
    number: 23,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Imperial Officers',
    id: 'F7-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Honor Guard',
    id: 'F7-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Rouge Admirals',
    id: 'F7-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Rouge Admirals',
    id: 'F7-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Court Enforcers',
    id: 'F7-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Court Enforcers',
    id: 'F7-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Imperial Defectors',
    id: 'F7-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Imperial Defectors',
    id: 'F7-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Commnad Chaos',
    id: 'F7-13',
    number: 13,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Imperial Defectors',
    id: 'F7-15',
    number: 15,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Imperial Defectors',
    id: 'F7-16',
    number: 16,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Mass Uprising',
    id: 'F7-17',
    number: 17,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Mass Uprising',
    id: 'F7-18',
    number: 18,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Faithful Disciples',
    id: 'F8-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'The Young Light',
    id: 'F8-16',
    number: 16,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Plot to Kidnap',
    id: 'F8-17',
    number: 17,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'The Prodigal One',
    id: 'F8-18',
    number: 18,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Secret Order',
    id: 'F8-19',
    number: 19,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'The Prophet',
    id: 'F8-25',
    number: 25,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Secret Order',
    id: 'F8-26',
    number: 26,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Call to Pilgrimage',
    id: 'F9-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Portal Seekers',
    id: 'F9-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Songs of the Banner',
    id: 'F10-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Mind Managers',
    id: 'F10-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Prison Wardens',
    id: 'F10-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Prison Wardens',
    id: 'F10-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Against Hegemony',
    id: 'F10-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Against Hegemony',
    id: 'F10-10',
    number: 1,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Sycophants',
    id: 'F11-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Planet Hammer',
    id: 'F11-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Forgeworld Refugees',
    id: 'F11-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Blazeworld Refugees',
    id: 'F11-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Deadworld Refugees',
    id: 'F11-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Lostworld Refugees',
    id: 'F11-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Heartworld Refugees',
    id: 'F11-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Planet-Eater Loose',
    id: 'F11-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Pirate Hoard',
    id: 'F12-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Pirate Fleet',
    id: 'F12-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Pirate Smugglers',
    id: 'F12-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Call to Action',
    id: 'F12-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Silver-Tongues',
    id: 'F12-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Spore Ships',
    id: 'F13-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Blight Fury',
    id: 'F13-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Blight Hunters',
    id: 'F13-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Blight Reapers',
    id: 'F13-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Blight Purge',
    id: 'F13-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Blight Purge',
    id: 'F13-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Blight Purge',
    id: 'F13-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Blight Panic',
    id: 'F13-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Blight Looms',
    id: 'F13-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Well of Empathy',
    id: 'F14-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Psionic Liaisons',
    id: 'F14-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Itinerant Empaths',
    id: 'F14-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Itinerant Empaths',
    id: 'F14-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Oath of Peace',
    id: 'F15-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Arsenal Keepers',
    id: 'F15-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Arms Interest',
    id: 'F15-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Arms Interest',
    id: 'F15-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'lore',
    name: 'Claims of Nobility',
    id: 'F16-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'lore',
    name: "Wardens's Levy",
    id: 'F16-12',
    number: 12,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Feast Day',
    id: 'F16-13',
    number: 13,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Feast Day',
    id: 'F16-14',
    number: 14,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Skirmishers',
    id: 'F16-15',
    number: 15,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Sworn Guardians',
    id: 'F16-16',
    number: 16,
  },
]);

export const allLawCards: RuleCard[] = withImages([
  {
    category: 'rule',
    type: 'law',
    name: 'Imperial Protectors',
    id: 'F1-08',
    number: 8,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Commonwealth Ambition',
    id: 'F2-14',
    number: 14,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Commonwealth Membership',
    id: 'F2-22',
    number: 22,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'War Profiteering',
    id: 'F3-20',
    number: 20,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Golems',
    id: 'F5-05',
    number: 5,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Golem Actions',
    id: 'F5-06',
    number: 6,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Partisan Seizing',
    id: 'F6-16',
    number: 16,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Faithful Cards',
    id: 'F8-13',
    number: 13,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Pluralistic Faith',
    id: 'F8-14',
    number: 14,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Doctrinal Faith',
    id: 'F8-23',
    number: 23,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Repressed Faith',
    id: 'F8-28',
    number: 28,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Banners of Hegemony',
    id: 'F10-03',
    number: 3,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Seats & Feifs',
    id: 'F16-09',
    number: 9,
  },
  {
    category: 'rule',
    type: 'law',
    name: 'Feudal Law',
    id: 'F16-10',
    number: 10,
  },
]);

export const allEdictCards: RuleCard[] = withImages([
  {
    category: 'rule',
    type: 'edict',
    name: 'Guild Envoys Depart',
    id: 'base-02',
    number: 2,
  },
  {
    category: 'rule',
    type: 'edict',
    name: 'Govern the Imperial Reach',
    id: 'base-03',
    number: 3,
  },
  {
    category: 'rule',
    type: 'edict',
    name: 'Govern the Imperial Reach',
    id: 'base-04',
    number: 5,
  },
  {
    category: 'rule',
    type: 'edict',
    name: 'Govern the Imperial Reach',
    id: 'base-05',
    number: 5,
  },
    {
    category: 'rule',
    type: 'edict',
    name: 'Imperial Quorum',
    id: 'F1-13',
    number: 2,
  },
  {
    category: 'rule',
    type: 'edict',
    name: 'Call For Armistice',
    id: 'F2-15',
    number: 25,
  },
  {
    category: 'rule',
    type: 'edict',
    name: 'Gain Monopolies',
    id: 'F3-18',
    number: 20,
  },
  {
    category: 'rule',
    type: 'edict',
    name: "Advocate's demand",
    id: 'F4-13',
    number: 45,
  },
  {
    category: 'rule',
    type: 'edict',
    name: "Guilds Decry Terror",
    id: 'F6-19',
    number: 75,
  },
  {
    category: 'rule',
    type: 'edict',
    name: "Use Imperial Foundries",
    id: 'F7-03',
    number: 55,
  },
  {
    category: 'rule',
    type: 'edict',
    name: "Set Doctrine",
    id: 'F8-21',
    number: 90,
  },
  {
    category: 'rule',
    type: 'edict',
    name: "Set Lay Doctrine",
    id: 'F8-27',
    number: 90,
  },
]);

export const allSummitCards: RuleCard[] = withImages([
  {
   category: 'rule',
    type: 'summit',
    name: 'Monopoly Consent',
     id: 'F3-19',
     number: 19,
 },
 {
   category: 'rule',
    type: 'summit',
    name: 'Guild Negotiations',
     id: 'F4-14',
     number: 14,
 },
 {
   category: 'rule',
    type: 'summit',
    name: 'Knowledge Set Free',
     id: 'F5-14',
     number: 14,
 },
]);

export const allActionCards: ActionCard[] = withImages([
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 9',
    id: 'F8-04',
    number: 9,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 8',
    id: 'F8-05',
    number: 8,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 7',
    id: 'F8-06',
    number: 7,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 6',
    id: 'F8-07',
    number: 6,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 5',
    id: 'F8-08',
    number: 5,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 4',
    id: 'F8-09',
    number: 4,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 3',
    id: 'F8-10',
    number: 3,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 2',
    id: 'F8-11',
    number: 2,
  },
  {
    category: 'action',
    type: 'faithful',
    name: 'Faithful Action 1',
    id: 'F8-12',
    number: 1,
  },
  {
  category: 'action',
  type: 'mobilization',
  name: 'Mobilization Action 1',
  id: 'MO-1',
  number: 1,
},
{
  category: 'action',
  type: 'mobilization',
  name: 'Mobilization Action 2',
  id: 'MO-2',
  number: 2,
},
{
  category: 'action',
  type: 'mobilization',
  name: 'Mobilization Action 3',
  id: 'MO-3',
  number: 3,
},
{
  category: 'action',
  type: 'mobilization',
  name: 'Mobilization Action 4',
  id: 'MO-4',
  number: 4,
},
{
  category: 'action',
  type: 'mobilization',
  name: 'Mobilization Action 5',
  id: 'MO-5',
  number: 5,
},
{
  category: 'action',
  type: 'mobilization',
  name: 'Mobilization Action 6',
  id: 'MO-6',
  number: 6,
},
{
  category: 'action',
  type: 'mobilization',
  name: 'Mobilization Action 7',
  id: 'MO-7',
  number: 7,
},

{
  category: 'action',
  type: 'administration',
  name: 'Administration Action 1',
  id: 'AD-1',
  number: 1,
},
{
  category: 'action',
  type: 'administration',
  name: 'Administration Action 2',
  id: 'AD-2',
  number: 2,
},
{
  category: 'action',
  type: 'administration',
  name: 'Administration Action 3',
  id: 'AD-3',
  number: 3,
},
{
  category: 'action',
  type: 'administration',
  name: 'Administration Action 4',
  id: 'AD-4',
  number: 4,
},
{
  category: 'action',
  type: 'administration',
  name: 'Administration Action 5',
  id: 'AD-5',
  number: 5,
},
{
  category: 'action',
  type: 'administration',
  name: 'Administration Action 6',
  id: 'AD-6',
  number: 6,
},
{
  category: 'action',
  type: 'administration',
  name: 'Administration Action 7',
  id: 'AD-7',
  number: 7,
},

{
  category: 'action',
  type: 'aggression',
  name: 'Aggression Action 1',
  id: 'AG-1',
  number: 1,
},
{
  category: 'action',
  type: 'aggression',
  name: 'Aggression Action 2',
  id: 'AG-2',
  number: 2,
},
{
  category: 'action',
  type: 'Aggression Action aggression',
  name: '3',
  id: 'AG-3',
  number: 3,
},
{
  category: 'action',
  type: 'aggression',
  name: 'Aggression Action 4',
  id: 'AG-4',
  number: 4,
},
{
  category: 'action',
  type: 'aggression',
  name: 'Aggression Action 5',
  id: 'AG-5',
  number: 5,
},
{
  category: 'action',
  type: 'Aggression Action aggression',
  name: '6',
  id: 'AG-6',
  number: 6,
},
{
  category: 'action',
  type: 'Aggression Action aggression',
  name: '7',
  id: 'AG-7',
  number: 7,
},

{
  category: 'action',
  type: 'construction',
  name: 'Construction Action 1',
  id: 'CO-1',
  number: 1,
},
{
  category: 'action',
  type: 'construction',
  name: 'Construction Action 2',
  id: 'CO-2',
  number: 2,
},
{
  category: 'action',
  type: 'construction',
  name: 'Construction Action 3',
  id: 'CO-3',
  number: 3,
},
{
  category: 'action',
  type: 'construction',
  name: 'Construction Action 4',
  id: 'CO-4',
  number: 4,
},
{
  category: 'action',
  type: 'construction',
  name: 'Construction Action 5',
  id: 'CO-5',
  number: 5,
},
{
  category: 'action',
  type: 'construction',
  name: 'Construction Action 6',
  id: 'CO-6',
  number: 6,
},
{
  category: 'action',
  type: 'construction',
  name: 'Construction Action 7',
  id: 'CO-7',
  number: 7,
},
{
  category: 'action',
  type: 'event',
  name: 'event1',
  id: 'EV-1',
  number: 1,
},
{
  category: 'action',
  type: 'event',
  name: 'event3',
  id: 'EV-3',
  number: 3,
},
{
  category: 'action',
  type: 'event',
  name: 'event2',
  id: 'EV-2',
  number: 2,
},
{
  category: 'action',
  type: 'event',
  name: 'eventCaretaker',
  id: 'F5-15',
  number: 15,
},
]);

export const allPlayerAreaCards: PlayerCard[] = withImages([
  {
    category: 'player',
    type: 'title',
    name: 'Founder of the Commonwealth',
    id: 'F2-13',
    number: 13,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Member of the Commonwealth',
    id: 'F2-18',
    number: 18,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Member of the Commonwealth',
    id: 'F2-19',
    number: 19,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Member of the Commonwealth',
    id: 'F2-20',
    number: 20,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Member of the Commonwealth',
    id: 'F2-21',
    number: 21,
  },
  {
    category: 'player',
    type: 'ability',
    name: 'Partisan Seizing',
    id: 'F6-03',
    number: 3,
  },
  {
    category: 'player',
    type: 'ability',
    name: 'Spreading the Faith',
    id: 'F8-03',
    number: 3,
  },
  {
    category: 'player',
    type: 'ability',
    name: 'Uncovering Clues',
    id: 'F9-02',
    number: 2,
  },
  {
    category: 'player',
    type: 'ability',
    name: 'Clues to the Portal',
    id: 'F9-03',
    number: 3,
  },
  {
    category: 'player',
    type: 'ability',
    name: 'Planting Banners',
    id: 'F10-02',
    number: 2,
  },
  {
    category: 'player',
    type: 'ability',
    name: 'Breaking Worlds',
    id: 'F10-03',
    number: 3,
  },
  {
    category: 'player',
    type: 'ability',
    name: 'Witnesses',
    id: 'F14-02',
    number: 2,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Lord of the 1st Cluster',
    id: 'F16-03',
    number: 3,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Lord of the 2nd Cluster',
    id: 'F16-04',
    number: 4,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Lord of the 3rd Cluster',
    id: 'F16-05',
    number: 5,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Lord of the 4th Cluster',
    id: 'F16-06',
    number: 6,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Lord of the 5th Cluster',
    id: 'F16-07',
    number: 7,
  },
  {
    category: 'player',
    type: 'title',
    name: 'Lord of the 6th Cluster',
    id: 'F16-08',
    number: 8,
  },
]);

/**
 * INITIAL ZONE CONTENTS
 * These are the cards that start inside each zone.
 */

/**
 * Court starts with the same 15 cards every time.
 */
export const initialCourtCards: CourtCard[] = withImages([{
    category: 'court',
    type: 'guild',
    name: 'Mining Interest',
    id: 'cc-01',
    number: 1,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Construction Union',
    id: 'cc-02',
    number: 2,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Gatekeepers',
    id: 'cc-03',
    number: 3,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Shipping Interest',
    id: 'cc-04',
    number: 4,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Skirmishers',
    id: 'cc-05',
    number: 5,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Arms Union',
    id: 'cc-06',
    number: 6,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Lattice Spies',
    id: 'cc-07',
    number: 7,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Silver-Tongues',
    id: 'cc-08',
    number: 8,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Sworn Guardians',
    id: 'cc-09',
    number: 9,
  },
  {
    category: 'court',
    type: 'guild',
    name: 'Elder Brokers',
    id: 'cc-10',
    number: 10,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Populist Demands',
    id: 'cc-11',
    number: 11,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Council Intrigue',
    id: 'cc-12',
    number: 12,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Diplomatic Fiasco',
    id: 'cc-13',
    number: 13,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Song of Freedom',
    id: 'cc-14',
    number: 14,
  },
  {
    category: 'court',
    type: 'vox',
    name: 'Blight Looms',
    id: 'cc-15',
    number: 15,
  },
]);

/**
 * These zones start empty.
 */
export const initialLawCards: RuleCard[] = [];
export const initialEdictCards: RuleCard[] = [];
export const initialSummitCards: RuleCard[] = [];

/**
 * AVAILABLE CARD POOLS
 * These are cards that exist and can be added later,
 * but do not start in the zone.
 *
 * Since all 15 court cards start in the court, there are currently
 * no extra available court cards outside the court.
 *
 * For rules, everything starts available and nothing starts placed.
 */
export const availableCourtCards: CourtCard[] = [];

export const availableLawCards: RuleCard[] = [...allLawCards];
export const availableEdictCards: RuleCard[] = [...allEdictCards];
export const availableSummitCards: RuleCard[] = [...allSummitCards];

export const availableActionCards: ActionCard[] = [...allActionCards];

export const initialPlayerAreaCards: PlayerCard[] = [];

export const availablePlayerAreaCards: PlayerCard[] = [...allPlayerAreaCards];
export const initialActionDeck: ActionCard[] = withImages([{
  category: 'action',
  type: 'mobilization',
  name: '1',
  id: 'MO-1',
  number: 1,
},
{
  category: 'action',
  type: 'mobilization',
  name: '2',
  id: 'MO-2',
  number: 2,
},
{
  category: 'action',
  type: 'mobilization',
  name: '3',
  id: 'MO-3',
  number: 3,
},
{
  category: 'action',
  type: 'mobilization',
  name: '4',
  id: 'MO-4',
  number: 4,
},
{
  category: 'action',
  type: 'mobilization',
  name: '5',
  id: 'MO-5',
  number: 5,
},
{
  category: 'action',
  type: 'mobilization',
  name: '6',
  id: 'MO-6',
  number: 6,
},
{
  category: 'action',
  type: 'mobilization',
  name: '7',
  id: 'MO-7',
  number: 7,
},

{
  category: 'action',
  type: 'administration',
  name: '1',
  id: 'AD-1',
  number: 1,
},
{
  category: 'action',
  type: 'administration',
  name: '2',
  id: 'AD-2',
  number: 2,
},
{
  category: 'action',
  type: 'administration',
  name: '3',
  id: 'AD-3',
  number: 3,
},
{
  category: 'action',
  type: 'administration',
  name: '4',
  id: 'AD-4',
  number: 4,
},
{
  category: 'action',
  type: 'administration',
  name: '5',
  id: 'AD-5',
  number: 5,
},
{
  category: 'action',
  type: 'administration',
  name: '6',
  id: 'AD-6',
  number: 6,
},
{
  category: 'action',
  type: 'administration',
  name: '7',
  id: 'AD-7',
  number: 7,
},

{
  category: 'action',
  type: 'aggression',
  name: '1',
  id: 'AG-1',
  number: 1,
},
{
  category: 'action',
  type: 'aggression',
  name: '2',
  id: 'AG-2',
  number: 2,
},
{
  category: 'action',
  type: 'aggression',
  name: '3',
  id: 'AG-3',
  number: 3,
},
{
  category: 'action',
  type: 'aggression',
  name: '4',
  id: 'AG-4',
  number: 4,
},
{
  category: 'action',
  type: 'aggression',
  name: '5',
  id: 'AG-5',
  number: 5,
},
{
  category: 'action',
  type: 'aggression',
  name: '6',
  id: 'AG-6',
  number: 6,
},
{
  category: 'action',
  type: 'aggression',
  name: '7',
  id: 'AG-7',
  number: 7,
},

{
  category: 'action',
  type: 'construction',
  name: '1',
  id: 'CO-1',
  number: 1,
},
{
  category: 'action',
  type: 'construction',
  name: '2',
  id: 'CO-2',
  number: 2,
},
{
  category: 'action',
  type: 'construction',
  name: '3',
  id: 'CO-3',
  number: 3,
},
{
  category: 'action',
  type: 'construction',
  name: '4',
  id: 'CO-4',
  number: 4,
},
{
  category: 'action',
  type: 'construction',
  name: '5',
  id: 'CO-5',
  number: 5,
},
{
  category: 'action',
  type: 'construction',
  name: '6',
  id: 'CO-6',
  number: 6,
},
{
  category: 'action',
  type: 'construction',
  name: '7',
  id: 'CO-7',
  number: 7,
},
]);